name: CI
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          pushd
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          popd
          .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: output_windows
          path: build/dist/override_tickrate.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove python2
        run: sudo apt-get remove python2 python2.7 && sudo apt-get autoremove

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang g++-multilib python3 python3-pip

      - name: Enable i386 packages
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -o APT::Immediate-Configure=false libcurl4-openssl-dev:i386

      - name: Build
        run:
          PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Collect Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output_linux
          path: build/dist
