name: CI
on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build
        run: |
          pushd
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\Launch-VsDevShell.ps1"
          popd
          pip install --upgrade setuptools wheel
          .\build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/dist/override_tickrate.zip

  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install clang g++-multilib python3 python3-pip

      - name: Build
        run:
          PATH=/home/runner/.local/bin:$PATH ./build.sh

      - name: Collect Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/dist/override_tickrate.tar.gz
